### ISSUE TITLE
Support for Latex results table

### ISSUE THREAD

**Issue by manoelcampos** [cloudsimplus/cloudsimplus#330]
Check [org.cloudsimplus.builders.tables](https://github.com/manoelcampos/cloudsimplus/tree/master/cloudsim-plus/src/main/java/org/cloudsimplus/builders/tables) package.
A new set of classes can be created based on TextTable related classes.

## Related Issues

- #328
- #329

**Comment by vaibhavkoshti7** [comment]
hello @manoelcampos ,I would like to work on this issue .

**Comment by manoelcampos** [comment]
Hey @vaibhavkoshti7
That is great. Probably, some design changes may be required in the current class hierarchy.
If you want to start working on this, just let me know and send a PR. 
You don't need to wait for it to be done to send the PR. This way, I can provide some guidance.

**Comment by marwenbenhajhassine** [comment]
Hello @manoelcampos , just letting you know that I'll be taking the initiative to address this issue.

**Comment by manoelcampos** [comment]
Great. Thank you. Let me know if you need some help

**Comment by marwenbenhajhassine** [comment]
I would like to know how to test the output ? should i download cloudsimplus-examples only to run a simple simulation, or is there a way to create a simulation class here?

**Comment by manoelcampos** [comment]
You can copy the BasicFirstExample and paste inside the cloudsim-plus src directory and change as needed.
This is the easiest way.

**Comment by marwenbenhajhassine** [comment]
Just to check, the input of the data is a csv file and the output is a latex table of it, correct?

**Comment by marwenbenhajhassine** [comment]
Hi, check out #490 and let me know your thoughts. :)
