### ISSUE TITLE
Broker VM creation retry causes infinite loop in some scenarios

### ISSUE THREAD

**Issue by manoelcampos** [cloudsimplus/cloudsimplus#349]
Remove the `broker0.setFailedVmsRetryDelay(-1)` in CostsExample1 to check that.
That may happen because VMs are never destroyed when become idle.
And since events to retry VM creation may be arriving all the time,
those VMs are never finished and the broker won't shut down.

See #348 for more details.

## Proposed solution

Introduce a broker `maxVmCreationRetries` attribute (default value should conform to failedVmsRetryDelay).
Another attribute named `currentVmCreationRetries` should be introduced to indicate the number of retries already made.
After all waiting VMs are successfully created, that attribute must be reset to the default value.

## Related Examples

Check https://github.com/cloudsimplus/cloudsimplus-examples/pull/5

**Comment by sohamchari** [comment]
Hi, I would like to work on this issue as my first PR.

**Comment by manoelcampos** [comment]
Thanks, feel free to send a PR. If you have any  doubts, please let me know.

**Comment by manoelcampos** [comment]
Hey @sohamchari 
Just let me know if you have started working on this.
You can send a PR anytime, regardless if the implementation is done or not.
This way, I can provide some guidance.

**Comment by sohamchari** [comment]
Hey, yes. I have started working on this. I shall send a PR soon. Currently, going through the broker code. I'll ask if I have any doubts here.

**Comment by sohamchari** [comment]
Hey, yes. I have started working on this. I shall send a PR soon. Currently, going through the broker code. I'll ask if I have any doubts here.

**Comment by sohamchari** [comment]
Hi @manoelcampos, wanted to ask a few things:
1. `maxVmCreationRetries` should indicate the maximum number of retries allowed and once `currentVmCreationRetries` hits the maximum limit, the retries should not be allowed. Please correct let me know if I am wrong.
2. Since now the examples are moved to the new repository, I should send the PR to the new repository.
This is my first contribution, please excuse me if the doubts sound very basic.

**Comment by sohamchari** [comment]
Hi @manoelcampos, I have sent PRs for both repositories. Do check it out and let me know about the PRs.
