### ISSUE TITLE
Provide a more precise way to perform CPU vertical scaling

### ISSUE THREAD

**Issue by henls** [cloudsimplus/cloudsimplus#381]
# ISSUE

## Actual behavior 

According to the example "VerticalVmCpuScalingExample.java" provided, when the number of VM cores is changed to 1, the scaling action is not as expected. Further checking the source code, I found that the resource utilization is calculated by `AllocatedResource/Capacity`, in order to consider if the resource is under or overload and then needs scaling. This is only true if the utilization model of the cloudlet is full, which can be found by simple modifications, such as modifying the utilization model "UtilizationModelFull"  to " UtilizationModelDynamic(0.5)". You will find the scaling process is same as “Full”,  as is changing it to dynamic(0.1).

## Expected behavior

The scaling process should be related to the occupancy of the MIPS and not just to the actual number of cores used. Consider VM PEs = 10, cloudlet number = 9 (each one requiring 1 core) and the utilization model is `UtilizationModelDynamic(0.1)`. 

At this point the VM utilization based on MIPS occupancy is `0.1 * 9 / 10 = 9%`. Using `Allocated/Capacity` the utilization is `9/10 = 90%`. As I understand it, the utilization collected on a actual server should be closer to 9% than 90%.

## If the issue is related to a specific method, provide a test case that fails in order to show the problem

Change line below to `final var utilizationCpu = new UtilizationModelDynamic(0.1);`

https://github.com/manoelcampos/cloudsimplus/blob/4b3667677f94d5eb7f999f041c69f90957c14b13/cloudsim-plus-examples/src/main/java/org/cloudsimplus/examples/autoscaling/VerticalVmCpuScalingExample.java#L364

## Specifications like the version of the project, operating system or workload file used

version=7.2.0
operating system=Ubuntu 18.04

**Comment by manoelcampos** [comment]
Hello @henls 

Thanks for your contribution. You are right.
The scaling would be more precise if it considers the total MIPS used instead of just the number of virtual CPUs (PEs).
However, changing that may not be so simple. I have to evaluate how to do it, because there are different kinds of resources that can be scaled, not just CPUs.

I'll get back to you ASAP.

**Comment by manoelcampos** [comment]
There is a `Vm.getTotalCpuMipsUtilization()` method that may be used for that purpose. But the issue is that the scaling works in a generic way for different kinds of resources (CPU, RAM, BW). Using that method, the CPU scaling will use a different way to check resource utilization. This way, I have to think about the modeling here.

**Comment by henls** [comment]
Hello @manoelcampos 
Hello
I have modified the simple CPU scaling code without considering other resource scaling and found another problem.
Using MIPS occupancy to scale resources relies on the cloudlet trace, so if the cloudlet is a long term load with 10% occupancy and one core, the resource scaling floor is set to 40% and there are 10 such loads. After a period of time the machine state will stabilise at 1 cpu, 10 simultaneous loads, 10% MIPS occupancy and 100% PEs utilisation. Intuitively, this scaling scheme is also not accurate.
If you want to experiment with google trace, MIPS occupancy is something to consider, because PE occupancy is independent of the cloudlets' trace, it is only related to the number of cloudlets. However, the above problem occurs when submitting multiple cloudlets and using MIPS occupancy, so maybe I should just run one cloudlet on the VM and use the MIPS occupancy scaling method.

**Comment by manoelcampos** [comment]
> I have modified the simple CPU scaling code without considering other resource scaling and found another problem.
> Using MIPS occupancy to scale resources relies on the cloudlet trace, 
I don't know what you exactly mean by "cloudlet trace". Do you mean "cloudlet resource utilization"?
That defines the VM load. This way, we have to track cloudlet execution.
Methods such as `Vm.getTotalCpuMipsUtilization()` computes MIPS utilization based on current running Cloudlets.

> so if the cloudlet is a long term load with 10% occupancy and one core, the resource scaling floor is set to 40% and there are 10 such loads. After a period of time the machine state will stabilise at 1 cpu, 10 simultaneous loads, 10% MIPS occupancy and 100% PEs utilisation. Intuitively, this scaling scheme is also not accurate.

I don't get what you mean.

> If you want to experiment with google trace, MIPS occupancy is something to consider, because PE occupancy is independent of the cloudlets' trace, it is only related to the number of cloudlets. However, the above problem occurs when submitting multiple cloudlets and using MIPS occupancy, so maybe I should just run one cloudlet on the VM and use the MIPS occupancy scaling method.

You are right. The number of running Cloudlets really defines the number of used PEs, regardless of the level of MIPS utilization. Using MIPS instead is more accurate.

**Comment by manoelcampos** [comment]
Closing due to lack of response.
