### ISSUE TITLE
VerticalVmScalingSimple is not working for RAM

### ISSUE THREAD

**Issue by henls** [cloudsimplus/cloudsimplus#392]
## Actual behavior 
When running VerticalVmRamScalingExample, the following error is prompted and it does not scale according to ram usage.

> INFO  160.22: VerticalVmScalingSimple: 0 Ram deallocated from Vm 0: new capacity is 800. Current resource usage is 100.0%
Time  160.2: Vm 0 Ram Usage: 100.00% ( 800 of  800 MB) | Host Ram Allocation:  84.00% (16800 of 20000 MB). Running Cloudlets: 2
WARN  161.22: CloudletSchedulerTimeShared: Cloudlet 4 requested 1000 Mbps of Bandwidth but no amount is available., which delays Cloudlet processing.
INFO  161.22: VerticalVmScalingSimple: 0 Ram deallocated from Vm 0: new capacity is 800. Current resource usage is 100.0%"

## Expected behavior

Normal scaling behavior

**Comment by ulfaric** [comment]
Hi,

Is this bug fixed? because when I run the Ram scaling example, the ram size still does not change. There is always a warning that ram resize failed due to unexpected error.

**Comment by greninja58** [comment]
Hi, is there any update on this issue, as vertical scaling isn't working properly, can it be fixed by changing or adding a setResourceAmountToScale method in the VerticalScaling class?

**Comment by manoelcampos** [comment]
I'll take a look on it this week.

**Comment by manoelcampos** [comment]
I've just fixed the issue and the 8.5.4 version will be available at Maven Central soon.
You may see that VM RAM utilization sometimes change to 100%.
That is another issue #429
