### ISSUE TITLE
Vertical Scaling bugs

### ISSUE THREAD

**Issue by ulfaric** [cloudsimplus/cloudsimplus#393]
## Actual behavior 
RAM vertical scaling always failed to resize. (Double-checked with the supported example for RAM scaling).
CPU could downsize to a negative number.

## If the issue is related to a specific method, provide a test case that fails in order to show the problem
RAM issue is consistent.
CPU downsize error happens when using send/receive tasks with network cloudlet, and the number/size of packets is too large.

## If it is a wider problem or you don't know where it happens, please provide a minimal simulation example which reproduces the problem
RAM - no fix found
CPU - limites the size

## Specifications like the version of the project, operating system or workload file used

7.3.0

**Comment by manoelcampos** [comment]
Duplicated with #392
