### ISSUE TITLE
Broker shutdown before cloudlets are finished

### ISSUE THREAD

**Issue by ulfaric** [cloudsimplus/cloudsimplus#394]
The broker shut down before all submitted cloudlets are finished. This happens when multiple cloudlets are assigned to a single VM. The warning suggests decreasing the minimum time between events, or the data center scheduling interval. But it does not help at all.

I also tried different VM allocation/schedule policies and cloudlet schedule policies, but it does not help either.

I have struggled with this since I start to use cloudsim plus. :(

**Comment by manoelcampos** [comment]
Hello @ulfaric, attach a minimalist example that show the issue and I'll check that.

**Comment by ulfaric** [comment]
Hi

This bug is not consistent. Sometimes, even you re-run the same code. It will magically work.

My theory is it is related to random number when you are using UilizationModelDynamic. But even I lock the seed, sometimes it still happens.

Also there is another more important bug, sometimes the broker will not finish cloudlets that are waiting in the queue, but directly shut-down. This happens whenever you have cloudlets that cannot be put on VM because lacking of available PEs.

**Comment by ulfaric** [comment]
For previous comments,  by "finish" I mean the broker will not even try to schedule them. Even some previous cloudlet has finished and there are PEs becoming available.

**Comment by manoelcampos** [comment]
If you use random numbers, you don't have deterministic events, despite a static seed is expected to yield the same results every time you run the example. Anyway, if you submit new Vms, the broker will try to assign waiting cloudlets to them.

Try the `setShutdownWhenIdle()` and `setVmDestructionDelay()` methods on the broker.

**Comment by manoelcampos** [comment]
Please let me know if that works.

**Comment by ulfaric** [comment]
Unfortunately, they do not. :(

I talked with my colleague who is a student of  a professor for Cloudbus lab. He said there may be something wrong for the event queue (according oringinal cloudsim).

He was unable to help with CloudSim plus. :(

**Comment by manoelcampos** [comment]
If you are able to create an example that reproduces the issue, I'll check that.
CloudSim Plus fixes several bugs inherited from CloudSim. 
I don't think there is an issue with the event queue. All events that arrived in the event queue are expected to be processed. If you are using PRNGs, that may cause such a kind of issue.

What are you using these PRNGs for?
If you use them to generate the length of cloudlets, I've seen this cause the same issue you are facing.
That happens when your PRNG is generating too granular cloudlet lengths.
For instance, instead of generating a length such as 10298 MI, you should generate lengths multiples of the MIPS capacity of the VM running the cloudlet. If your VM has PE with 10000 MIPS, your cloudlets should have lengths multiple of that value.

Try that and let me know.

**Comment by ulfaric** [comment]
I found out the condition for it to 100% happens.

The simulation will shut down prematurely if:

1.  the last list of cloudlets is submitted to VM, so no more cloudlet is waiting currently.
2. The schedule interval is smaller than the length of the last submitted cloudlets.

So it looks like something send out a termination signal to the simulation too early.

**Comment by ulfaric** [comment]
================== Starting CloudSim Plus 7.3.0 ==================

INFO  0.00: Datacenter is starting...
INFO  ms-0 is starting...
INFO  ms-1 is starting...
INFO  ms-2 is starting...
INFO  ms-3 is starting...
INFO  ms-4 is starting...
INFO  ms-5 is starting...
INFO  Entities started.
INFO  0.00: ms-0: List of 1 datacenters(s) received.
INFO  0.00: ms-0: Trying to create Vm 0 in Datacenter
INFO  0.00: ms-1: List of 1 datacenters(s) received.
INFO  0.00: ms-1: Trying to create Vm 0 in Datacenter
INFO  0.00: ms-2: List of 1 datacenters(s) received.
INFO  0.00: ms-2: Trying to create Vm 0 in Datacenter
INFO  0.00: ms-3: List of 1 datacenters(s) received.
INFO  0.00: ms-3: Trying to create Vm 0 in Datacenter
INFO  0.00: ms-4: List of 1 datacenters(s) received.
INFO  0.00: ms-4: Trying to create Vm 0 in Datacenter
INFO  0.00: ms-5: List of 1 datacenters(s) received.
INFO  0.00: ms-5: Trying to create Vm 0 in Datacenter
INFO  0.00: VmAllocationPolicyBestFit: Vm 0 has been allocated to Host 0/DC 1
INFO  0.00: VmAllocationPolicyBestFit: Vm 0 has been allocated to Host 0/DC 1
INFO  0.00: VmAllocationPolicyBestFit: Vm 0 has been allocated to Host 0/DC 1
INFO  0.00: VmAllocationPolicyBestFit: Vm 0 has been allocated to Host 0/DC 1
INFO  0.00: VmAllocationPolicyBestFit: Vm 0 has been allocated to Host 0/DC 1
INFO  0.00: VmAllocationPolicyBestFit: Vm 0 has been allocated to Host 0/DC 1
INFO  0.01: ms-0: List of 1 Cloudlets submitted to the broker during simulation execution.
INFO  Cloudlets creation request sent to Datacenter.
INFO  0.01: ms-0: Sending Cloudlet 0 to Vm 0 in Host 0/DC 1.
INFO  0.01: ms-0: All 1 waiting Cloudlets submitted to some VM.
INFO  0.01: ms-1: List of 1 Cloudlets submitted to the broker during simulation execution.
INFO  Cloudlets creation request sent to Datacenter.
INFO  0.01: ms-1: Sending Cloudlet 0 to Vm 0 in Host 0/DC 1.
INFO  0.01: ms-1: All 1 waiting Cloudlets submitted to some VM.
INFO  0.01: ms-2: List of 1 Cloudlets submitted to the broker during simulation execution.
INFO  Cloudlets creation request sent to Datacenter.
INFO  0.01: ms-2: Sending Cloudlet 0 to Vm 0 in Host 0/DC 1.
INFO  0.01: ms-2: All 1 waiting Cloudlets submitted to some VM.
INFO  0.01: ms-3: List of 1 Cloudlets submitted to the broker during simulation execution.
INFO  Cloudlets creation request sent to Datacenter.
INFO  0.01: ms-3: Sending Cloudlet 0 to Vm 0 in Host 0/DC 1.
INFO  0.01: ms-3: All 1 waiting Cloudlets submitted to some VM.
INFO  0.01: ms-4: List of 1 Cloudlets submitted to the broker during simulation execution.
INFO  Cloudlets creation request sent to Datacenter.
INFO  0.01: ms-4: Sending Cloudlet 0 to Vm 0 in Host 0/DC 1.
INFO  0.01: ms-4: All 1 waiting Cloudlets submitted to some VM.
INFO  0.01: ms-5: List of 1 Cloudlets submitted to the broker during simulation execution.
INFO  Cloudlets creation request sent to Datacenter.
INFO  0.01: ms-5: Sending Cloudlet 0 to Vm 0 in Host 0/DC 1.
INFO  0.01: ms-5: All 1 waiting Cloudlets submitted to some VM.
INFO  0.01: ms-3: List of 5 Cloudlets submitted to the broker during simulation execution.
INFO  Cloudlets creation request sent to Datacenter.
INFO  0.01: ms-3: Sending Cloudlet 1 to Vm 0 in Host 0/DC 1.
INFO  0.01: ms-3: Sending Cloudlet 2 to Vm 0 in Host 0/DC 1.
INFO  0.01: ms-3: Sending Cloudlet 3 to Vm 0 in Host 0/DC 1.
INFO  0.01: ms-3: Sending Cloudlet 4 to Vm 0 in Host 0/DC 1.
INFO  0.01: ms-3: Sending Cloudlet 5 to Vm 0 in Host 0/DC 1.
INFO  0.01: ms-3: All 5 waiting Cloudlets submitted to some VM.
INFO  0.60: ms-0: Cloudlet 0 finished in Vm 0 and returned to broker.
INFO  0.60: ms-1: Cloudlet 0 finished in Vm 0 and returned to broker.
INFO  0.60: ms-2: Cloudlet 0 finished in Vm 0 and returned to broker.
INFO  0.60: ms-3: Cloudlet 0 finished in Vm 0 and returned to broker.
INFO  0.60: ms-4: Cloudlet 0 finished in Vm 0 and returned to broker.
INFO  0.60: ms-5: Cloudlet 0 finished in Vm 0 and returned to broker.
INFO  1.61: Processing last events before simulation shutdown.
INFO  1.61: ms-0 is shutting down...
INFO  1.61: ms-0: Requesting Vm 0 destruction.
INFO  1.61: ms-2 is shutting down...
INFO  1.61: ms-2: Requesting Vm 0 destruction.
INFO  1.61: ms-4 is shutting down...
INFO  1.61: ms-4: Requesting Vm 0 destruction.
INFO  1.61: DatacenterSimple: Vm 0 destroyed on Host 0/DC 1.
INFO  1.61: DatacenterSimple: Vm 0 destroyed on Host 0/DC 1.
INFO  1.61: DatacenterSimple: Vm 0 destroyed on Host 0/DC 1.
INFO  1.61: ms-1 is shutting down...
INFO  1.61: ms-1: Requesting Vm 0 destruction.
INFO  1.61: ms-5 is shutting down...
INFO  1.61: ms-5: Requesting Vm 0 destruction.
INFO  1.61: DatacenterSimple: Vm 0 destroyed on Host 0/DC 1.
INFO  1.61: DatacenterSimple: Vm 0 destroyed on Host 0/DC 1.
INFO  1.61: ms-3 is shutting down...
INFO  1.61: ms-3: Requesting Vm 0 destruction.
WARN  1.61: DatacenterSimple: Vm 0 destroyed on Host 0/DC 1. It had a total of 5 cloudlets (running + waiting). Some events may have been missed. You can try: (a) decreasing CloudSim's minTimeBetweenEvents and/or Datacenter's schedulingInterval attribute; (b) increasing broker's Vm destruction delay for idle VMs if you set it to zero; (c) defining Cloudlets with smaller length (your Datacenter's scheduling interval may be smaller than the time to finish some Cloudlets).
INFO  Simulation: No more future events

INFO  CloudInformationService0: Notify all CloudSim Plus entities to shutdown.

INFO
================== Simulation finished at time 1.61 ==================

**Comment by ulfaric** [comment]
So from my log, the simulation shutdown at 1.61 but there are still 5 cloudlet on ms-3 VM 0 is not finished.

**Comment by manoelcampos** [comment]
> I found out the condition for it to 100% happens.
In that case, please make a minimal example and attach here, please.

> The simulation will shut down prematurely if:
> 
> 1. the last list of cloudlets is submitted to VM, so no more cloudlet is waiting currently.
When you submit new cloudlets, the submitCloudletList() method calls requestDatacentersToCreateWaitingCloudlets().
So, this shouldn't happen. 

> 2. The schedule interval is smaller than the length of the last submitted cloudlets.
> 
> So it looks like something send out a termination signal to the simulation too early.

The scheduling interval will usually be smaller than the length of cloudlets. What you have to keep in mind to avoid issues is to set that interval as an integer and make cloudlet lengths multiple of such interval.
Such a kind of issue already happened in CloudSim and I've identified some of them, fixed a few, but I'm not able to deep dive on this.

**Comment by manoelcampos** [comment]
> So from my log, the simulation shutdown at 1.61 but there are still 5 cloudlet on ms-3 VM 0 is not finished.

If your simulation is finishing in just 1.61 second, you are creating too small cloudlets and that is the case where such a kind of issue will happen.

**Comment by ulfaric** [comment]
No, it should not finish at that time. The simulation shuts down regardless there are still 5 cloudlets running. I even reduced the minimum time between events to 0.00000001. It still happens.

I have pretty much given up by now. :(

**Comment by manoelcampos** [comment]
As I said, If you provide an minimal example, I take a look and try to track down the issue.
You can attach it here. Without a running example, it's difficult to understand what you are doing,
mainly how you are using the PRNGs.

**Comment by ulfaric** [comment]
This turns out maybe my fault. I have combined a broker, a VM and some other attributes into a new class object, which I consider more like a microservice. This object consumes another object I created called flow to create cloudlet and submit it onto its own broker.

Turns out my flow transfer from one microservice to another has a issue, that it could be lost.

**Comment by manoelcampos** [comment]
Ok. Closing the issue.
