### ISSUE TITLE
Network Cloudlet Tasks setMemory() does not work

### ISSUE THREAD

**Issue by ulfaric** [cloudsimplus/cloudsimplus#395]
I am trying to use NetworkCLoudlet. After I add execution/send/receive tasks with intended memory usage by using setMemory() function. There is no memory usage at all.

**Comment by vineetjain27** [comment]
hey @ulfaric  i want to work into this issue please accept my contribution

**Comment by jlxcsong** [comment]
您好！您发的邮件我已收到！

**Comment by manoelcampos** [comment]
Hey @ulfaric 
This `setMemory()` method is inherited from CloudSim and it has no effect.
If you want to define show a cloudlet uses RAM, you have to set a `UtilizationModel`
using the `Cloudlet.setUtilzationModelRam()` method.
I'll just remove this method and close the issue.

**Comment by manoelcampos** [comment]
`setMemory` method even has a TODO comment explaining it's useless.
