### ISSUE TITLE
RAM at 100% Usage before cloudlet submission

### ISSUE THREAD

**Issue by OrdinaryDev83** [cloudsimplus/cloudsimplus#397]
## Description
Create a bunch or VMs without submitting any cloudlets.
Try to access the RAM with a fonction listening to the simulation's clock.

## Actual behavior 
The RAM is at 100% usage even though no cloudlet is in.

## Expected behavior
The RAM should be at 0% usage.

**Comment by manoelcampos** [comment]
Hello @OrdinaryDev83 
Sorry for the late reply. Please attache a minimal example that shows the issue and I'll check that ASAP.

**Comment by ulfaric** [comment]
This one doesn't need a example. It constantly has this issue. After a VM is created, the bw and RAM usage will be full. And if a VM finished a cloudlet, the bw and RAM will be left as the same value when the cloudlet finishes.

My work around is, in VM creation listener, add a cloudlet with length 1 and use full CPU, 0 RAM and BW.

For all cloudlet (the one you want to simulate), in finish listener, add that length 1 cloudlet again to reset the RAM and BW usage.

**Comment by manoelcampos** [comment]
In order to check the issue and try to help and fix it, I really need a working example.
That makes things easier to fix.

**Comment by manoelcampos** [comment]
If you was able to see the issue, you already have an example. Just try to make it as simple as possible and attach it here.
