### ISSUE TITLE
Dead links (404) in "Main Features" section in Readme.

### ISSUE THREAD

**Issue by StruffelProductions** [cloudsimplus/cloudsimplus#403]
To report an issue or feature request, you have to provide the information below.

# WHEN REPORTING AN ISSUE:

## Actual behavior 
The links for the points 17,18,19,22,23,24 in the "Main Exclusive Features" section of the Readme all point to dead links.

## Expected behavior
The links should point to the examples they are supposed to reference. 

## If the issue is related to a specific method, provide a test case that fails in order to show the problem
I think the links have not been adjusted for the new 'cloudsimplus-examples' repository.

## If it is a wider problem or you don't know where it happens, please provide a minimal simulation example which reproduces the problem
N/A

## Specifications like the version of the project, operating system or workload file used
Latest version of master branch (f4551b8d2db3f7e9adf322a2c7d7e1fa47001056)

**Comment by manoelcampos** [comment]
Hey @StruffelProductions 
Thanks for noticing that. Just fixed the links.
