### ISSUE TITLE
VmMapper error in DatacenterBrokerBestFit

### ISSUE THREAD

**Issue by jmsw4bn** [cloudsimplus/cloudsimplus#451]
In DatacenterBrokerBestFit, a cloudlet can be delivered to a destroied VM.
I think this error is caused by "getVmCreatedList()" in the defaultVmMapper.
Should "getVmCreatedList()"  be "getVmExecList()"?

In addition, it seems that a submissiondelayed cloudlet will be bounded to a VM, although the time haven't reach its submissiondelay time?
As a result, the VM may destroied when the cloudlet is actually submitted, but it can still process the cloudlet.

**Comment by manoelcampos** [comment]
You are right. That is exactly what DatacenterBrokerSimple does.

**Comment by manoelcampos** [comment]
Thanks for reporting. I've just fixed the issue.

> In addition, it seems that a submissiondelayed cloudlet will be bounded to a VM, although the time haven't reach its submissiondelay time? As a result, the VM may destroied when the cloudlet is actually submitted, but it can still process the cloudlet.

That won't happen. If you check DatacenterBrokerAbstract.createWaitingCloudlets, even if the cloudlet is bound to a specific VM, the method sends a message to the datacenter with the given submission delay.
