### ISSUE TITLE
Expected finish time when there is memory Oversubscription is resulting in negative values

### ISSUE THREAD

**Issue by ivo1r2** [cloudsimplus/cloudsimplus#460]
## Actual behavior 
If the value "VM_RAM" in the example "VirtualMemoryForRequestedRamHigherThanAvailableExample" is changed from 1000 to 10000 and the memory of the host is changed from 2048 to 20480, the resulting "Expected finish time (if no over-subscription)" value is negative for some cloudlets. 

## Expected behavior
The "Expected finish time (if no over-subscription)" value should be a realistic positive value.

**Comment by manoelcampos** [comment]
Thanks for reporting and sorry for the delay. I've just fixed the issue.
