### ISSUE TITLE
the result of simulation makes me confused

### ISSUE THREAD

**Issue by Qiu-Weidong** [cloudsimplus/cloudsimplus#470]
I created one host and one Vm on CloudSimPlus. And then I created two cloudlets, while their cloudlength are both 80000MI.

first, I submitted the two cloudlets at time 0.0, and both of them were finished at  11.5, spending 11.4s .
![image](https://github.com/cloudsimplus/cloudsimplus/assets/63244731/d8668303-5e07-4c90-ba0e-df897cb3a037)

And then I submitted the first cloudlet at time 0.0s, and the second at time 3.0s. Both of them are also finished at 11.5s, while one has run for 11.4s and another has only run for 8.5s.
![image](https://github.com/cloudsimplus/cloudsimplus/assets/63244731/d8769c86-a051-4f74-b21a-4aded40b2c33)

Finily, I submited the second cloudlet at time 8.0s. and the second cloudlet has only run for 3.5s.
![image](https://github.com/cloudsimplus/cloudsimplus/assets/63244731/e3734c02-95f8-4489-b90e-ce1c7514a42d)

the result makes me confused. Besides, if I submit the second cloudlet after the first finishes, the second cloudlet run faster than the first, despite they are totally same.
![image](https://github.com/cloudsimplus/cloudsimplus/assets/63244731/4e3ac9fe-6d32-48ea-9f4a-095bd2dca6db)

I use a `CloudSimEntity` to submit cloudlet dynamicly, I override the `processEvent` function and in the `processEvent` function, I use `DatacenterBroker::submitCloudletList` function to submit the cloudlets.

**Comment by manoelcampos** [comment]
If you are resubmitting the same Cloudlets that may be the issue.
But if you are overriding some framework methods, you may be doing something wrong.
Confirm that the issue happens without changing those methods or provide a minimal example (with only the necessary code to show the issue), including the changes you made on those overridden methods.

**Comment by manoelcampos** [comment]
Closing the issue due to lack of reply.
