### ISSUE TITLE
NetworkCloudlet finish is not being identified correctly, causing VMs to be destroyed without starting up its Cloudlets

### ISSUE THREAD

**Issue by manoelcampos** [cloudsimplus/cloudsimplus#475]
The NetworkVmsExampleWorkflowApp shows the issue.

See https://github.com/cloudsimplus/cloudsimplus/discussions/372

# Version

CloudSim Plus 8.5.1

**Comment by Inverseit** [comment]
Do you happen to have any updates on this issue? Can you let us know a version of Cloudsim where this works?

**Comment by JoaoNevesSoares** [comment]
Hello, this is still not working at all. Is there any way that I could debug this issue ?

**Comment by manoelcampos** [comment]
I'll take a look by the end of next week.
