### ISSUE TITLE
cloudlet's setLifeTime() is ignored with default schedulingInterval

### ISSUE THREAD

**Issue by deRemo** [cloudsimplus/cloudsimplus#476]
## Actual behavior 
The cloudlet's ExecTime does not stop at the specified life time values when the scheduling interval of the datacenter is configured to 0 (default)

## Expected behavior
The simulation should comply with the maximum time cloudlets are allowed to execute regardless of the scheduling interval

## If the issue is related to a specific method, provide a test case that fails in order to show the problem
Set SCHEDULING_INTERVAL = 0 in `CloudletLifeTimeExample.java` to see that the cloudlet's ExecTime does not stop at the specified CLOUD_LIFE_TIME value

## Specifications like the version of the project, operating system or workload file used
Cloudsimplus 8.5.1

**Comment by manoelcampos** [comment]
You don't need permission to send a PR. Maybe the issue is because you just cloned the repository without creating a fork first. Is that the case?

**Comment by deRemo** [comment]
Ah, yes it is, I didn't fork, I just pushed the intellij project. No
problem, I'll fix that in a few minutes

**Comment by deRemo** [comment]
This is also closely related to cloudsimplus/cloudsimplus-examples#13
