### ISSUE TITLE
When I implemented a custom genetic algorithm by imitating the simulated annealing algorithm provided in the cloudsimplus project, I created a GeneticAlgorithmAbstract class, and its constructor reported the following error

### ISSUE THREAD

**Issue by fellow-me** [cloudsimplus/cloudsimplus#501]
### error
'HeuristicAbstract(org.cloudsimplus.distributions.@lombok.NonNull ContinuousDistribution, java.lang.@lombok.NonNull Class<S>)' is not public in 'org.cloudsimplus.heuristics.HeuristicAbstract'. Cannot be accessed from outside package
### picture
![image](https://github.com/user-attachments/assets/1a1333fc-0f1e-472f-b575-bf44c7450d01)
### question
How can I implement my heuristic algorithm by CloudSimPlus?

**Comment by jlxcsong** [comment]
您好！您发的邮件我已收到！

**Comment by fellow-me** [comment]
package com.qiujie.ga;

import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;
import org.cloudsimplus.distributions.ContinuousDistribution;
import org.cloudsimplus.heuristics.HeuristicAbstract;
import org.cloudsimplus.heuristics.HeuristicSolution;


@Accessors @Getter
public abstract class GeneticAlgorithmAbstract<S extends HeuristicSolution<?>> extends HeuristicAbstract<S> {

    @Setter
    private int populationSize;

    @Setter
    private double maxGeneration;

    private double currentGeneration;

    @Setter
    private double mutationRate;

    GeneticAlgorithmAbstract(final ContinuousDistribution random, final Class<S> solutionClass){
        super(random, solutionClass);
    }

    @Override
    public double getAcceptanceProbability() {
        return 0.0;
    }

    /**
     * {@inheritDoc}
     *
     * @return true if the system is cold enough and solution search can be
     * stopped, false otherwise
     */
    @Override
    public boolean isToStopSearch() {
        return currentGeneration > maxGeneration;
    }

    @Override
    public void updateSystemState() {
        currentGeneration++;
	    LOGGER.debug(
	        "{}: Best solution cost so far is {}, current generation is {}",
            System.currentTimeMillis(), getBestSolutionSoFar().getCost(), getCurrentGeneration());
    }


}
@jlxcsong 这是我写的代码

**Comment by manoelcampos** [comment]
Sorry for the delay. The issue has just been fixed.
